### PR TITLE
:recycle: move react to peer dependencies

### LINKED ISSUE #4: move react to peerDeps
React dependency could cause 2 react instances installed:
https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375#.wvy7xpwn2

### PR DESCRIPTION
**Pull request by Guria**
fix #4

### CODE REVIEW

**Comment by mistadikay** [comment]
could you please leave only peerDeps in your PR? I'll bump devDeos in a separate commit

**Comment by mistadikay** [comment]
I mean transfer `react` from `deps` to `devDeps` as is (`"react": "0.14.x",`)

**Comment by Guria** [comment]
So I should leave peerDeps with support of 15-rc, but devDeps with 0.14.x only?

**Comment by deepsweet** [comment]
yes, because we didn't test react@0.15 yet, so tests may fall.

**Comment by Guria** [comment]
done

**Pull request merged**
