### PR TITLE
:heavy_plus_sign: typescript definition

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by deepsweet** [comment]
```js
import { BEMEntity } from 'rebem-classname'
```

will it be somehow resolved with `typings` field in package.json? I see only `BEMEntityProps` interface exported from `rebem-classname`.

**Comment by Guria** [comment]
@deepsweet I have renamed it already in 'rebem-classname'

**Comment by Guria** [comment]
https://github.com/rebem/classname/pull/1/files#diff-0e3ac3694919aca1db302bc3ebe669f2R1

**Comment by deepsweet** [comment]
landed with v0.8.0 (also you have to bump start-rebem-preset with `npm update`)

**Pull request merged**
